#!/bin/sh
# -*- coding: utf-8-unix -*-
# vim:fileencoding=utf-8:ff=unix
# @(#) Command line tool to send wake on LAN packet.

# Copyright (c) 2014 eel3
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
#     1. The origin of this software must not be misrepresented; you must not
#     claim that you wrote the original software. If you use this software
#     in a product, an acknowledgment in the product documentation would be
#     appreciated but is not required.
#
#     2. Altered source versions must be plainly marked as such, and must not be
#     misrepresented as being the original software.
#
#     3. This notice may not be removed or altered from any source
#     distribution.

set -u
umask 0022
IFS=$(printf ' \t\n_'); IFS=${IFS%_}
PATH=/bin:/usr/bin
export IFS LC_ALL=C LANG=C PATH

readonly progname="${0##*/}"
readonly version=2.1.2.20220710

# usage <exit-code>
usage() {
    echo "usage: $progname [-hv] [-a IP-address] [-p port] <MAC-address>" 1>&2
    exit "$1"
}

# version (no parameter)
version() {
    echo "$progname $version" 1>&2
    exit 0
}

# error <message>
error() {
    echo "$progname:" ${@+"$@"} 1>&2
    exit 1
}

# tomac <MAC address>
tomac() {
    hex='[0-9a-f]{2}'

    echo "$1" |
    sed 's/^[ \t]*//' |
    sed 's/[ \t]*$//' |
    tr '\n -' ':::' |
    sed 's/:$//' |
    grep -E -i "^$hex:$hex:$hex:$hex:$hex:$hex\$"
}

# topn <port number>
topn() {
    [ "$1" -eq 0 ] 2>/dev/null
    [ $? -lt 2 ] || return 1
    [ "$1" -ge 1 ] && [ "$1" -le 65535 ] || return 1
    echo "$1"
}

# main routine

ipaddr=255.255.255.255
port=2304

opt=
while getopts 'a:hp:v' opt; do
    case $opt in
    a)      ipaddr="$OPTARG" ;;
    h)      usage 0 ;;
    p)      port=$(topn "$OPTARG") ;;
    v)      version ;;
    \?)     usage 1 ;;
    esac
done
shift $((OPTIND - 1))

[ $# -eq 1 ] || usage 1

macaddr=$(tomac "$1")
readonly macaddr
[ -n "$macaddr" ] || error 'invalid MAC address'
[ -n "$ipaddr" ] || error 'no IP address'
[ -n "$port" ] || error 'no/invalid port number'

wolp "$macaddr" | nc -n -u -w 1 "$ipaddr" "$port"
