#!/bin/sh
# @(#) command line tool to make wake on LAN packet. Version 1.0.0.20140608

# Copyright (c) 2014 eel3
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
#     1. The origin of this software must not be misrepresented; you must not
#     claim that you wrote the original software. If you use this software
#     in a product, an acknowledgment in the product documentation would be
#     appreciated but is not required.
#
#     2. Altered source versions must be plainly marked as such, and must not be
#     misrepresented as being the original software.
#
#     3. This notice may not be removed or altered from any source
#     distribution.

PATH=/bin:/usr/bin

readonly progname=`basename "$0"`

# usage <status>
usage() {
    echo "usage: $progname [-h] <MAC address>" 1>&2
    exit $1
}

# error <message>
error() {
    echo "$progname:" "$@" 1>&2
    exit 1
}

# tohex <MAC address>
tohex() {
    local hex='[1-9a-f]{2}'

    echo "$1" |
    sed 's/^[ \t]*//' |
    sed 's/[ \t]*$//' |
    tr '\n -' ':::' |
    sed 's/:$//' |
    grep -E -i "^$hex:$hex:$hex:$hex:$hex:$hex\$" |
    sed 's/:/ 0x/g' |
    sed 's/^/0x/'
}

opt=
while getopts 'h' opt; do
    case $opt in
    h)      usage 0 ;;
    \?)     usage 1 ;;
    esac
done
shift `expr $OPTIND - 1`

[ $# -eq 1 ] || usage 1

hex=`tohex "$1"`
[ -n "$hex" ] || error 'invalid MAC address'

oct=`printf '\\%03o\\%03o\\%03o\\%03o\\%03o\\%03o' $hex`

printf '\377\377\377\377\377\377'
for i in `seq 1 16`; do printf "$oct"; done
