#!/bin/sh
# -*- coding: utf-8-unix -*-
# vim:fileencoding=utf-8:ff=unix
# @(#) Command line tool to make wake on LAN packet.

# Copyright (c) 2014 eel3
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
#     1. The origin of this software must not be misrepresented; you must not
#     claim that you wrote the original software. If you use this software
#     in a product, an acknowledgment in the product documentation would be
#     appreciated but is not required.
#
#     2. Altered source versions must be plainly marked as such, and must not be
#     misrepresented as being the original software.
#
#     3. This notice may not be removed or altered from any source
#     distribution.

set -u
umask 0022
IFS=$(printf ' \t\n_'); IFS=${IFS%_}
PATH=/bin:/usr/bin
export IFS LC_ALL=C LANG=C PATH

readonly progname=${0##*/}
readonly version=1.1.0.20190405

# usage <exit-code>
usage() {
    echo "usage: $progname [-hv] <MAC address>" 1>&2
    exit $1
}

# version (no parameter)
version() {
    echo "$progname $version" 1>&2
    exit 0
}

# error <message>
error() {
    echo "$progname:" ${@+"$@"} 1>&2
    exit 1
}

# tohex <MAC address>
tohex() {
    local hex='[1-9a-f]{2}'

    echo "$1" |
    sed 's/^[ \t]*//' |
    sed 's/[ \t]*$//' |
    tr '\n -' ':::' |
    sed 's/:$//' |
    grep -E -i "^$hex:$hex:$hex:$hex:$hex:$hex\$" |
    sed 's/:/ 0x/g' |
    sed 's/^/0x/'
}

# main routine

opt=
while getopts 'hv' opt; do
    case $opt in
    h)      usage 0 ;;
    v)      version ;;
    \?)     usage 1 ;;
    esac
done
shift $(($OPTIND - 1))

[ $# -eq 1 ] || usage 1

hex=$(tohex "$1")
[ -n "$hex" ] || error 'invalid MAC address'

oct=$(printf '\\%03o\\%03o\\%03o\\%03o\\%03o\\%03o' $hex)

printf '\377\377\377\377\377\377'
for i in `seq 1 16`; do printf "$oct"; done
